spring.application.name=Ferreteria
#Configuraciones generales de la BD
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=sandbox;encrypt=true;trustServerCertificate=true
spring.datasource.username=rogelio.root
spring.datasource.password=15dtv0089R
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#Configuraciones JPA
spring.jpa.hibernate.ddl-auto=update
